### ISSUE TITLE
CSS - JS -  Fallbacks (perhaps for docs?)

### ISSUE THREAD

**Issue by flashtopia** [jsdelivr/bootstrapcdn#110]
Wanted to share a bit of code that can be used to fall back on local versions in case NetDNA is not available. (highly unlikely).  Jquery is required.   First JS fallback tests to see if bootstrap modals are enabled, if not then assumes NetDNA is down and loads js locally.  CSS fallback is done by checking for CSS color from bootstrap.css files; if not found attaches a local body to dom head. 

```
<!-- BOOTSTRAP JS WITH LOCAL FALLBACK-->
<script type="text/javascript" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>

<script> if(typeof($.fn.modal) === 'undefined') {document.write('<script src="//www.mysite.com/js/v/bootstrap-2.1.1.js"><\/script>')}</script>

<!-- BOOTSTRAP CDN FALLBACK CSS-->
<script>$(document).ready(function() {
var bodyColor = $('body').css("color"); if(bodyColor != 'rgb(51, 51, 51)') {$("head").prepend("<link rel='stylesheet' href='//www.mysite.com/css/fw/bootstrap-combined-2.1.1.css' type='text/css' media='screen'>");}
});</script>
```

**Comment by jam65st** [comment]
I use this fallback, but if in the custom class you change the body color then the **fallback runs** too and load twice. Then I was do a bit change:

```
<!-- BOOTSTRAP JS WITH LOCAL FALLBACK-->
<script type="text/javascript" src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js"></script>

<script>
  cdnFail = (typeof($.fn.modal) === 'undefined')
  if( cdnFail ) {
    document.write('<script src="//www.mysite.com/js/v/bootstrap-2.1.1.js"><\/script>')
  }
</script>

<!-- BOOTSTRAP CDN FALLBACK CSS-->
<script>
  $(document).ready(function() {
    if( cdnFail ) {
      $("head").prepend("<link rel='stylesheet' href='//www.mysite.com/css/fw/bootstrap-combined-2.1.1.css' type='text/css' media='screen'>");
    }
  });
</script>
```

**Comment by JKAussieSkater** [comment]
@flashtopia, is there a way to check if the Bootstrap JavaScript has loaded **without** using jQuery?
I wasn't sure if this is possible (given that Bootstrap JS is written in jQuery).

**Comment by jam65st** [comment]
@JKAussieSkater you need jquery allways, but you need test if JQuery was be loaded after jquery script line and if bootstrap.min.js was be loaded after the ir script line. In booth cases you need express your fallback in js. In my case I was create a variable **cdnFail** becouse if con fail, then I need load a local bootstrap.min.css

**Comment by JKAussieSkater** [comment]
Thanks for your insight @jam65st.
I do understand that jQuery must be loaded before bootstrap.min.js, and that the fallbacks need to be written in JS; I have it setup that way in my project too 😀
Perhaps my problem seems a bit unusual (given the necessary symbiotic relationship of jQuery and Bootstrap), but I was hoping to test if bootstrap.min.js had loaded using plain old JS (without jQuery).
My use case is that I'm trying to develop an error detection script, currently it says

> jQuery is not loaded
> We cannot confirm if Bootstrap.js has or hasn't loaded without jQuery

But if Bootstrap.js HAS loaded correctly, I want it to say is this instead:
> jQuery is not loaded
> Bootstrap.js has loaded successfully, although it requires jQuery

Do you think JS could be used to detect if Bootstrap.js has loaded?

**Comment by jam65st** [comment]
@JKAussieSkater May be you can try something like:

`var test = 'xxxx://--- Your Bootstrap source ---'; 
// method to detect if any script (src) was be loaded in js
function getScript( src ){
	var answer = false;
	var scriptNodes = document.getElementsByTagName( 'script' );
	// review loaded scripts (since this point)
	for ( i = 0; i < scriptNodes.length; i++ ){
		if( scriptNodes[i].src == src ){
			answer = true;
			// stop loop if success
			break;
		}
	}
	return answer;
}

// jQuery load test
jqueryLoaded = !(typeof jQuery === 'undefined');
// Bootstrap.min.js load test
bootstrapLoaded = getScript( test );

// Actions like you want do
console.log( 'jQuery is' + ( (jqueryLoaded) ? ' ' : ' not ' ) + 'loaded\nBootstrap.js has' + ( (bootstrapLoaded) ? ' ' : ' not ' ) + 'loaded successfully' + ( (jqueryLoaded) ? '' : ' although it requires jQuery' ) + '.' );`

**Comment by JKAussieSkater** [comment]
That's very clever; I love your code optimisations too! Thank you @jam65st !
