### ISSUE TITLE
bootstrapCDN certificates are showing as not valid

### ISSUE THREAD

**Issue by dblackw** [jsdelivr/bootstrapcdn#1738]
Looks like the certificate expired 13/10/2021 ... 
<img width="303" alt="Capture" src="https://user-images.githubusercontent.com/12490991/138176124-2fed1be2-1508-4c74-9ca2-b92287e225fe.PNG">

**Comment by jimaek** [comment]
1. What URL are you hitting?
2. Ping it and tell me the IP address
3. Make sure you have updated your browser and there is no MITM proxies being used

**Comment by ximsce** [comment]
Can confirm I'm seeing the https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js expired cert on cashortrade.org's website. I'm guessing it's a bad node, because I went across town and it magically started working again.

**Comment by dblackw** [comment]
I switched to Google DNS and they work fine, showing cloudflare certificates now. The  DNS was set to my ISP previously.
