### ISSUE TITLE
Who runs `maxcdn.bootstrapcdn.com` and `stackpath.bootstrapcdn.com`?

### ISSUE THREAD

**Issue by cdrx** [jsdelivr/bootstrapcdn#1749]
Are requests to these (legacy?) domains delivered using the jsDelivr infrastructure, or are these provided by a different CDN?

Is use of these domains covered by the [jsDelivr privacy policy](https://www.jsdelivr.com/terms/privacy-policy-jsdelivr-net)?

**Comment by jimaek** [comment]
Hey, we own and control the legacy endpoints as well. And yes the same policy applies.

**Comment by cdrx** [comment]
Thanks. Does jsDelivr offer the option for EU based companies to sign a data processing agreement for use of the CDN?

**Comment by jimaek** [comment]
Sure, we can help with that. Just email dak@prospectone.io

**Comment by cdrx** [comment]
👍
