### ISSUE TITLE
Blocked by CORS Policy

### ISSUE THREAD

**Issue by UsgsMonkey** [jsdelivr/bootstrapcdn#1757]
Greetings, 

Just in the last few days, we've run into issues running our Leaflet-based web portal @ https://hydromaintenance.nationalmap.gov/hmp which makes use of BootstrapCdn due to apparent CORS conflicts ...

![image](https://user-images.githubusercontent.com/26445758/159782503-355b5a2e-9cf6-44c1-8c58-502692b375cd.png)

We are using an older vintage of the library - but this is by necessity since it's a dependency of our Leaflet framework.  Here are our existing stylesheet linkages:

```
<!-- Load Bootstrap 3.3.7: Latest compiled and minified CSS (requires JQuery) -->
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

<!-- Load Bootstrap 3.3.7: Optional theme (requires JQuery) -->
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">

<!-- Load Bootstrap 3.3.6: necessary somehow for styles to properly render; may want to reconsider
resetting original Bootstrap version to 3.3.6 -->
<link rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
      integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
      crossorigin="anonymous">
```
Any assistance would be greatly appreciated!!!  This is an important website that we need to keep live to serve our partners.

Regards,

Brett
Dev Lead
USGS NGTOC

**Comment by jimaek** [comment]
I have a feeling its not a CORS issue. Can you please try to open the file directly and see what you get?
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

Do it on the same computer the screenshot came from. Additionally please ping "maxcdn.bootstrapcdn.com" and tell me the IP address you get

**Comment by UsgsMonkey** [comment]
It looks like I get a 504 error when I try to hit the CSS directly via Chrome.  Pinging the address gets me the following...

![image](https://user-images.githubusercontent.com/26445758/159784751-e774bb70-5c96-4bab-bafa-f507bb154691.png)

When I try to reach the address outside the VPN firewall, I can reach it successfully - but that doesn't help our website :P

**Comment by UsgsMonkey** [comment]
I'm in contact with internal IT.  Hopefully this can be resolved with their assistance.

**Comment by jimaek** [comment]
Can you actually traceroute it? And how does the 504 error look like?
Because I think it's a LAN issue on your side, maybe a firewall?

**Comment by UsgsMonkey** [comment]
I think you're right.  Good thought on tracert.  I'm forwarding the issue to our IT.  Sorry for the trouble and thanks for the assist.
