### ISSUE TITLE
Error in activation link

### ISSUE THREAD

**Issue by nonat0** [jsdelivr/bootstrapcdn#1810]
![error](https://github.com/jsdelivr/bootstrapcdn/assets/155467247/684f3c96-98c4-4888-9660-c018cb6f65bc)

the copy/paste link avaliable to use bootstrap contains a typing error that prevents its use. please check the image.

**Comment by nonat0** [comment]
Because is written as: fortawesome, instead of fontawesome, it prevents the users to use the link.

**Comment by jimaek** [comment]
Fort Awesome is the organization that owns Font Awesome, so there is no typo :)
