### ISSUE TITLE
Update to 5.3.3?

### ISSUE THREAD

**Issue by dandv** [jsdelivr/bootstrapcdn#1811]
How is this the "official" Bootstrap CDN when its [latest version is 5.3.2](https://www.bootstrapcdn.com/) while [jsdelivr has 5.3.3](https://www.jsdelivr.com/package/npm/bootstrap)?

**Comment by jimaek** [comment]
The CDN itself contains the latest release automatically and it's official because it's recommended by Bootstrap itself. 

The website has a delay when updating the versions in the UI. It has no impact on users or the CDN.

In any case that should be fixed shortly
