### ISSUE TITLE
Paper and Sandstone not working

### ISSUE THREAD

**Issue by maxrabin** [jsdelivr/bootstrapcdn#337]
Trying to load
- https://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/sandstone/bootstrap.min.css
- http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/sandstone/bootstrap.min.css
- https://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/paper/bootstrap.min.css
- http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/paper/bootstrap.min.css

I get

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>614BF981DA9D4EAF</RequestId>
  <HostId>wrtKEAGowj1nv2lfTVRfdxnRikOXksTV7ZZSRyMpSjbfvwIUrlUqm67L7uo0ajmH</HostId>
</Error>
```

**Comment by diegojancic** [comment]
I'm using Drupal's release version and I still get Access Denied for this one:
http://netdna.bootstrapcdn.com/bootswatch/3.0.2/paper/bootstrap.min.css
Other themes work, but not this one for this specific version.
Can this be fixed?  Thanks!
