### ISSUE TITLE
CDN is down

### ISSUE THREAD

**Issue by veera** [jsdelivr/bootstrapcdn#344]
http://netdna.bootstrapcdn.com/

CDN Link is down

**Comment by sean-hill** [comment]
It's down right now too.

**Comment by jdorfman** [comment]
@sean-hill looking into it

**Comment by sean-hill** [comment]
@jdorfman thanks :) It's now completely "down" it's just taking about 45 seconds to load.

**Comment by jdorfman** [comment]
@sean-hill yeah working with our engineering team.

**Comment by jdorfman** [comment]
@sean-hill it is isolated in Los Angeles.  Still unexceptable but that is the latest I know.

**Comment by sean-hill** [comment]
@jdorfman I don't know if this helps, but I'm in Phoenix, AZ and still having issues connecting to `https://www.bootstrapcdn.com/`.

**Comment by jdorfman** [comment]
@sean-hill yeah AZ routes to LA.  Try now.

**Comment by sean-hill** [comment]
@jdorfman Works like a charm!

**Comment by jdorfman** [comment]
@sean-hill awesome.  Sorry for the inconvenience.  We will be updating status.maxcdn.com with a post mortem.

**Comment by geri777** [comment]
status.maxcdn.com could have a form to add issues - similar to this one:
http://allestoerungen.de/stoerung/netflix
This is a real time analyses of user problems - users just click a button, categorize thir problem and the issue is counted in a heat map.
