### ISSUE TITLE
Access-Control-Allow-Origin header missing

### ISSUE THREAD

**Issue by ghost** [jsdelivr/bootstrapcdn#474]
Difference in headers when `?v=xx` is included. See below.

curl -v http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff

Date: Thu, 11 Dec 2014 15:44:10 GMT
< Content-Type: application/font-woff
< Content-Length: 65452
< Last-Modified: Mon, 08 Sep 2014 21:27:58 GMT
< ETag: "d95d6f5d5ab7cfefd09651800b69bd54"
< Server: NetDNA-cache/2.2
< Expires: Sun, 06 Dec 2015 15:44:10 GMT
< Cache-Control: max-age=31104000
< Vary: Accept-Encoding
< Access-Control-Allow-Origin: *
< X-Hello-Human: You should work for us! Email: jdorfman+theheader@maxcdn.com or @MaxCDNDeveloper on Twitter
< X-Cache: HIT
< Accept-Ranges: bytes
< Via: 1.1 SC13300_83_77
< Connection: keep-alive
# 

The below is the ACTUAL headers when requested by Chrome:

curl -v http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0

Content-Length: 65452
< Content-Type: application/font-woff
< ETag: "d95d6f5d5ab7cfefd09651800b69bd54"
< Server: NetDNA-cache/2.2
< Expires: Sun, 06 Dec 2015 15:16:03 GMT
< Last-Modified: Mon, 08 Sep 2014 21:27:58 GMT
< Connection: keep-alive
< Date: Thu, 11 Dec 2014 15:42:42 GMT

**Comment by geraldyeo** [comment]
I'm getting this error on my own server using the cdn link, so I tried on codepen.io and got the same error:

```
Font from origin 'http://maxcdn.bootstrapcdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.
```

[Codepen demo](http://codepen.io/geraldyeo/pen/OPWbbm)

curl is showing the header though:
`curl -I http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css`

```
HTTP/1.1 200 OK
Date: Thu, 08 Jan 2015 09:46:16 GMT
Content-Type: text/css
Content-Length: 21984
Connection: keep-alive
Last-Modified: Tue, 26 Aug 2014 20:38:35 GMT
ETag: "feda974a77ea5783b8be673f142b7c88"
Server: NetDNA-cache/2.2
Expires: Sun, 03 Jan 2016 09:46:16 GMT
Cache-Control: max-age=31104000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
X-Hello-Human: You should work for us! Email: jdorfman+theheader@maxcdn.com or @MaxCDNDeveloper on Twitter
X-Cache: HIT
Accept-Ranges: bytes
```

**Comment by lucastan** [comment]
Is this happening on Chrome? I found a workaround by using https instead as I couldnt find a good fix for this problem

**Comment by lucastan** [comment]
If i recall correctly chrome will still complain even when the header is present, not sure why. Https is the way to go

**Comment by geraldyeo** [comment]
@lucastan It is happening on Chrome & Firefox, not on Safari though. But yes you're right, https fixed it.

**Comment by zdravkoggeorgiev** [comment]
Some proxy in the middle cant strip **Access-Control-Allow-Origin** header too, I run in such situation. <br /> In most cases **https** encrypts transfer between you and the server, and proxy can't strip the headers. But **if** the proxy is your corporate proxy, and your local admin uses AD and can configure your computer, he can also configure proxy to filter your **https** requests. The only solution then is to test from remote computer outside of your network

**Comment by CrearPaginaWeb** [comment]
Thanks Lucastan ;)

**Comment by devzsolt** [comment]
**Access-Control-Allow-Origin** header is missing now...
```
$ curl -I "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0"
HTTP/1.1 200 OK
Content-Length: 65452
Content-Type: application/font-woff
ETag: "d95d6f5d5ab7cfefd09651800b69bd54"
Server: NetDNA-cache/2.2
Expires: Thu, 27 Apr 2017 03:56:33 GMT
Last-Modified: Thu, 19 Mar 2015 03:20:51 GMT
Connection: keep-alive
Date: Mon, 02 May 2016 04:03:01 GMT
```

**Comment by jmervine** [comment]
@devzsolt Not sure how/why but it looks like your headers are getting munged some how...

```
jmervine@laptop ~ $ curl -I "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0"
HTTP/1.1 200 OK
Date: Mon, 02 May 2016 16:09:00 GMT
Content-Type: application/font-woff
Content-Length: 65452
Connection: keep-alive
Last-Modified: Thu, 19 Mar 2015 03:20:51 GMT
ETag: "d95d6f5d5ab7cfefd09651800b69bd54"
Server: NetDNA-cache/2.2
Expires: Thu, 27 Apr 2017 16:09:00 GMT
Cache-Control: max-age=31104000
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
X-Hello-Human: You should work for us! Email: jdorfman+theheader@maxcdn.com or @MaxCDNDeveloper on Twitter
X-Cache: HIT
Accept-Ranges: bytes
```

**Comment by raitucarp** [comment]
Still happening now on Chrome  v 51.0.2704.106

**Comment by jdorfman** [comment]
@raitucarp which file in particular?

**Comment by raitucarp** [comment]
I think font-awesome, I got this message from mongoosejs docs:
```
Font from origin 'http://maxcdn.bootstrapcdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mongoosejs.com' is therefore not allowed access
```

**Comment by jdorfman** [comment]
@raitucarp please try now.

**Comment by raitucarp** [comment]
still

![Image of Yaktocat](http://image.prntscr.com/image/4874400dfc6f4ab9ab61c9316e15365c.png)

**Comment by jdorfman** [comment]
@raitucarp Give me a list of ALL urls and assets in question. I am not able to replicate the issue by going to `http://mongoosejs.com/docs/guide.html`

In fact all I see is `GET https://cse.google.com/cse/cse.js?cx=012173159455227967368:uvscsuqjovs 404 ()`

**Comment by raitucarp** [comment]
@jdorfman OK. It occures when I go to http://mongoosejs.com/docs/api.html in desktop mode, I browse using latest Google Chrome not canary.

**Comment by jdorfman** [comment]
Can't replicate it.

UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36`

![image](https://cloud.githubusercontent.com/assets/398230/16394942/7d0b9ec0-3c6c-11e6-9dd9-4efd8309b3b5.png)

![image](https://cloud.githubusercontent.com/assets/398230/16394953/84bee4f6-3c6c-11e6-86ce-9d78fcae1284.png)

All assets have the header:

```
$ for i in eot woff woff2 ttf svg; do echo ${i} && curl -Is maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.${i} |grep Access-Control-Allow-Origin; done
eot
Access-Control-Allow-Origin: *
woff
Access-Control-Allow-Origin: *
woff2
Access-Control-Allow-Origin: *
ttf
Access-Control-Allow-Origin: *
svg
Access-Control-Allow-Origin: *
```

I am having zero complaints from others, and trust me if there is an issue, Twitter tells me about it.  Not sure where else to go to from here.

**Comment by raitucarp** [comment]
Hmm, I don't know, why I have this. I'll back later, and figure it out what the real happening to me. The obvious thing that the icon won't load, and it seems that .woff and ttf don't get ```Access-Control-Allow-Origin: *``` header here
