### ISSUE TITLE
Enable DNSSEC

### ISSUE THREAD

**Issue by XhmikosR** [jsdelivr/bootstrapcdn#954]

**Comment by jdorfman** [comment]
@XhmikosR for www or cdn?

**Comment by XhmikosR** [comment]
This is for the whole domain, if I remember correctly.

**Comment by petarpetrovic** [comment]
I've escalated the request to the System Engineering team. Will let you know once this is done.

**Comment by XhmikosR** [comment]
@petarpetrovic: any news?

**Comment by petarpetrovic** [comment]
@XhmikosR still working with the System Engineering team on getting this enabled. Will ping them again today for an update.

**Comment by XhmikosR** [comment]
@petarpetrovic: ping

**Comment by petarpetrovic** [comment]
@XhmikosR this will need to get delayed a little bit due to the migration to the new CDN platform. I'll post more details and ETA as soon as I have it.

**Comment by jdorfman** [comment]
@XhmikosR I have a call with StackPath tomorrow, when we are ready to move over we will make sure this is applied. The new hostname going forward will be `stackpath.bootstrapcdn.com`. More on that after the move.

**Comment by petarpetrovic** [comment]
Due to the current limitations on Route 53's end, DNSSEC cannot be enabled at this time. I will be monitoring the Route 53 feature set and I'll revisit this issue once there are any new developments related to DNSSEC on their end.

**Comment by XhmikosR** [comment]
@jimaek can you please enable DNSSEC too?

**Comment by jimaek** [comment]
Honestly I prefer not to. I feel that it's too risky. Using multiple DNS providers would become complicated as well as migrating between different DNS providers, and it adds another point of failure to the system. 
I want to keep our systems portable to allow us to move fast in case something happens.
